name: Rust

on: [push, pull_request]

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt -- --check

  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build (default features)
      run: cargo build
    - name: Build (no features)
      run: cargo build --no-default-features
    - name: Build (all features)
      run: cargo build --all-features
    - name: Run Tests (default features)
      run: cargo test
    - name: Run Tests (no features) 
      run: cargo test --no-default-features
    - name: Run Tests (all features)
      run: cargo test --all-features

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clippy (default features)
      run: cargo clippy
    - name: Clippy (no features)
      run: cargo clippy --no-default-features
    - name: Clippy (all features)
      run: cargo clippy --all-features


